# Site settings
name: Jessica
email: jtieman2@illinois.edu
job_title: Grad student
institution: UIUC
institution_URL: http://www.illinois.edu
twitter_username: jessicairene
github_username: jtieman2

# Build settings
markdown: kramdown
permalinks: pretty
